<a href="https://colab.research.google.com/github/christianloring/Thinkful-assignments/blob/main/multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import fetch_20newsgroups_vectorized
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import  classification_report, confusion_matrix

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.datasets import load_digits
X, y = load_digits(return_X_y=True)

In [ ]:
X, y

(array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]), array([0, 1, 2, ..., 8, 9, 8]))

In [ ]:
np.bincount(y)

array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

We can see the 1797 samples, and 115098 data points (the 1797 arrays with 64 entries each). 

We see that each bin is roughly equal in size to each other, with the maximum difference between two bins being a difference of 9 (max diff ~5%)

In [ ]:
import numpy as np

print('The number of rows in the dataset is {:d}'.format(y.size))
print('The number of features in the dataset is {:d}'.format(X[1].size))
np.bincount(y)

The number of rows in the dataset is 1797
The number of features in the dataset is 64


array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

In [ ]:
from sklearn.model_selection import train_test_split
#Split the dataset into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 40)

In [ ]:
# Imports here
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score

lr_clf = LogisticRegression(solver='lbfgs', multi_class='ovr', max_iter=1000)
lr_cv_scores = cross_val_score(lr_clf, X, y, cv = 5)

print('Accuracy scores for the 5 folds: ', lr_cv_scores)
print('Mean cross validation score: {:.3f}'.format(lr_cv_scores.mean()))

Accuracy scores for the 5 folds:  [0.90833333 0.87777778 0.94428969 0.9637883  0.8913649 ]
Mean cross validation score: 0.917


In [ ]:
# Imports here
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=24)
rf_cv_scores = cross_val_score(rf_clf, X, y, cv = 5)

print('Accuracy scores for the 5 folds: ', rf_cv_scores)
print('Mean cross validation score: {:.3f}'.format(rf_cv_scores.mean()))

Accuracy scores for the 5 folds:  [0.92222222 0.89444444 0.94150418 0.94428969 0.91086351]
Mean cross validation score: 0.923
